### ISSUE TITLE
[Bug] No way to exit game and was able to open a terminal from game

### ISSUE THREAD

**Issue by hel1ow0r1d** [yxue5/CSE442#58]
There's no way to exit the game when I am done, and while randomly trying to exit the game, I encountered that I can open the terminal from game by pressing the " ` " button (located above the Tab key on the keyboard). Here's a picture attached at the bottom.
![screenshot 467](https://user-images.githubusercontent.com/35990813/38447489-18e3b7b8-39ed-11e8-96bb-364799bb7015.png)

**Comment by yxue5** [comment]
Hey Matt, we really appreciate all the feedback you've given for our game.  These issues will be fixed in the Beta Build where there will be an exit game option and the developer terminal is turned off.
