### ISSUE TITLE
Alpha Testing: Feature Request--Environment Damages Enemy/Opponent? 

### ISSUE THREAD

**Issue by kart2k15** [yxue5/CSE442#73]
Hey,
Can there be a feature-- such that if a player performs a certain combo/attack or throws the enemy at some specific point in the environment, hence cause more damage to their opponents health! Such as if you throw an opponent offthe ship, they lose half the health (or KO), or through a wall (then it causes additional damage, besides the attack itself)? @yxue5

**Comment by yxue5** [comment]
Hey Kart,
We have many plans for this game moving forward, but unfortunately we don't plan on implementing such a feature for the scope of this class.
Best,
Yang
