### ISSUE TITLE
Difficulty level (Feature request)

### ISSUE THREAD

**Issue by Nazat95** [yxue5/CSE442#83]
You could add a difficulty level system where in level 1 you fight an easy enemy. As you beat the enemies the game starts to get more difficult and maybe there is a final boss to fight. Also if multiplayer is added then there can be scoreboard showing player progression.

**Comment by yxue5** [comment]
Hey Nazat,
Our future direction for this game will indeed feature multiplayer, but that will likely not be done in the scope of this class. You can expect the AI to be tougher overall in the next release, bur our main focus right now is expanding the character moveset.

Best regards,
Yang
